services:
  currency-exchange:
    build:
      context: ./01-currency-exchange-microservice-basic/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    # networks:
    #   - currency-compose-network

  currency-conversion:
    build:
      context: ./02-currency-conversion-microservice-basic
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    restart: always
    environment:
      CURRENCY_EXCHANGE_SERVICE_HOST: http://currency-exchange:8000
    depends_on:
      - currency-exchange
    # networks:
    #   - currency-compose-network
  
# Networks to be created to facilitate communication between containers
# networks:
#   currency-compose-network: