name: CI Pipeline

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Docker Push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: owenwijaya22
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push currency exchange
        uses: docker/build-push-action@v6
        with:
          context: ./01-currency-exchange-microservice-basic/
          push: true
          tags: |
            owenwijaya22/microservices-currency-exchange:${{ github.run_number }}
            owenwijaya22/microservices-currency-exchange:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push currency conversion
        uses: docker/build-push-action@v6
        with:
          context: ./02-currency-conversion-microservice-basic/
          push: true
          tags: |
            owenwijaya22/microservices-currency-conversion:${{ github.run_number }}
            owenwijaya22/microservices-currency-conversion:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
