name: CI Build and Push Docker Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Docker Push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Layer Caching
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: owenwijaya22
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push currency exchange service
        run: |
          DOCKER_BUILDKIT=1 docker build ./01-currency-exchange-microservice-basic/ \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache-new,mode=max \
            -t owenwijaya22/microservices-currency-exchange:${{ github.run_number }} \
            -t owenwijaya22/microservices-currency-exchange:latest
          docker push owenwijaya22/microservices-currency-exchange:${{ github.run_number }}
          docker push owenwijaya22/microservices-currency-exchange:latest

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Build and push currency conversion service
        run: |
          DOCKER_BUILDKIT=1 docker build ./02-currency-conversion-microservice-basic/ \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache-new,mode=max \
            -t owenwijaya22/microservices-currency-conversion:${{ github.run_number }} \
            -t owenwijaya22/microservices-currency-conversion:latest
          docker push owenwijaya22/microservices-currency-conversion:${{ github.run_number }}
          docker push owenwijaya22/microservices-currency-conversion:latest

      - name: Move cache final
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
