name: CI Pipeline

on:
  push:
    branches: [ "master" ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Docker Push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: owenwijaya22
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push currency exchange service
        uses: docker/build-push-action@v5
        with:
          context: ./01-currency-exchange-microservice-basic/
          push: true
          tags: |
            owenwijaya22/microservices-currency-exchange:${{ github.run_number }}
            owenwijaya22/microservices-currency-exchange:latest

      - name: Build and push currency conversion service
        uses: docker/build-push-action@v5
        with:
          context: ./02-currency-conversion-microservice-basic/
          push: true
          tags: |
            owenwijaya22/microservices-currency-conversion:${{ github.run_number }}
            owenwijaya22/microservices-currency-conversion:latest
